# This is a basic workflow to help you get started with Actions

name: Docker Pipiline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
  #Deploy
      - name: Script
        run: |
           docker build -t frontend app/.
           echo login -u ${{ secrets.DOCKER_USER }} -p {{ secrets.DOCKER_SECRETS }} --stdin-password
           docker tag frontend brunosantos88/frontend
           docker push brunosantos88/frontend
          
