name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main ]
  workflow_dispatch:

jobs:


  build:

    runs-on: ubuntu-latest

    steps:


    - uses: actions/checkout@v2
    - name: login the Docker image
      run: docker login -u brunosantos88 -p ${{ secrets.DOCKER_TOKEN }}

    - name: Build the Docker App image
      run: docker build -t frontend app/.
    
    - name: Build the Docker mysql image
      run: docker build -t database mysql/.
      
    - name: Tag Docker frontend
      run: docker tag frontend brunosantos88/frontend

    - name: Tag Docker Database
      run: docker tag database brunosantos88/database
      
    - name: Push the Docker frontend
      run: docker push brunosantos88/frontend

    - name: Push the Docker database
      run: docker push brunosantos88/database


---
name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test # Add your deployment name here.

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: github@bootcamp-363315.iam.gserviceaccount.com
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Set up google cluster
    - name: Set up Cluster
      run: |-
       gcloud container clusters get-credentials meu-cluster --${{ env.GKE_ZONE }} --${{ secrets.GKE_PROJECT }}

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: kubectl apply -f
       app-deployment.yml
       load-balancer.yml
       secrets.yml